### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by seanwash** [seanwash/dnc-site#2]
- [x] Figure out a real deploy strategy (For now I used docker-machine to connect to DO and deploy the first instance).
- [x] Meta/OG tags
- [x] Gzip? & other perf things
- [x] Search
- [ ] Pagination (Could wait until the SC api update happens?)
- [ ] Sponsor page (http://layout.fm/)
- [ ] Stickers?
- [ ] Host / Producer list
- [ ] Feedback (Simple email or a form posting to a google sheet?)
